### ISSUE TITLE
Mount local volume for development.

### ISSUE THREAD

**Issue by heyMP** [contentacms/contenta_docker#12]
For development, I think it's a must to mount a shared volume to the Contenta root path so I can check-in the drupal codebase. Something like:

```
services:
  content_sync:
    build: ./contenta
    volumes:
      - www:/var/www
      - ./contenta/web:/var/www/web
```

However, I don't know if it's possible to mount a shared volume to a named volume.  I'm still relatively new to Docker so I don't know if there is a solution and possible workaround.
